apiVersion: apiextensions.r3d.sh/v1
kind: CustomResourceDefinition
metadata:
  name: store.dac.r3d.sh
spec:
  group: dac.r3d.sh
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      builtin:
        name: secret
        spec:
          url: "http://localhost"
          method: "GET"
  scope: Cluster
  names:
    plural: secrets
    singular: secret
    kind: Secret
    shortNames:
    - sc
